// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SulamaSistemiWebApi.Data;

#nullable disable

namespace SulamaSistemiWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250706210253_NewDeviceModels")]
    partial class NewDeviceModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SulamaSistemiWebApi.Models.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("LastOperationBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("SulamaSistemiWebApi.Models.RainSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RainLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RainSensors");
                });

            modelBuilder.Entity("SulamaSistemiWebApi.Models.TemperatureHumidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TemperatureHumidities");
                });
#pragma warning restore 612, 618
        }
    }
}
